name = "HelloPythonAndJulia"
uuid = "e81e8ffc-e45b-4154-9335-0c9e6b9d1870"
authors = ["Daniel Ingraham <d.j.ingraham@gmail.com>"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
